export type BibleBook = {
  testamentOrder: number;
  bibleOrder: number;
  newTestament: boolean;
  chapterCount: number;
  name: string;
  abbreviations: string[];
};

const bibleBooks: BibleBook[] = [
  { testamentOrder: 1, bibleOrder: 1, newTestament: false, chapterCount: 50, name: "Genesis", abbreviations: ["Gen", "Ge", "Gn"] },
  { testamentOrder: 2, bibleOrder: 2, newTestament: false, chapterCount: 40, name: "Exodus", abbreviations: ["Ex", "Exod"] },
  { testamentOrder: 3, bibleOrder: 3, newTestament: false, chapterCount: 27, name: "Leviticus", abbreviations: ["Lev", "Le", "Lv"] },
  { testamentOrder: 4, bibleOrder: 4, newTestament: false, chapterCount: 36, name: "Numbers", abbreviations: ["Num", "Nu", "Nm", "Nb"] },
  { testamentOrder: 5, bibleOrder: 5, newTestament: false, chapterCount: 34, name: "Deuteronomy", abbreviations: ["Deut", "De", "Dt"] },
  { testamentOrder: 6, bibleOrder: 6, newTestament: false, chapterCount: 24, name: "Joshua", abbreviations: ["Josh", "Jos", "Jsh"] },
  { testamentOrder: 7, bibleOrder: 7, newTestament: false, chapterCount: 21, name: "Judges", abbreviations: ["Judg", "Jdg", "Jg", "Jdgs"] },
  { testamentOrder: 8, bibleOrder: 8, newTestament: false, chapterCount: 4, name: "Ruth", abbreviations: ["Ruth", "Rth", "Ru"] },
  { testamentOrder: 9, bibleOrder: 9, newTestament: false, chapterCount: 31, name: "1 Samuel", abbreviations: ["1 Sam", "1 Sm", "1 Sa", "1 S"] },
  { testamentOrder: 10, bibleOrder: 10, newTestament: false, chapterCount: 24, name: "2 Samuel", abbreviations: ["2 Sam", "2 Sm", "2 Sa", "2 S"] },
  { testamentOrder: 11, bibleOrder: 11, newTestament: false, chapterCount: 22, name: "1 Kings", abbreviations: ["1 Kings", "1 Kgs", "1 Kin", "1 Ki"] },
  { testamentOrder: 12, bibleOrder: 12, newTestament: false, chapterCount: 25, name: "2 Kings", abbreviations: ["2 Kings", "2 Kgs", "2 Kin", "2 Ki"] },
  { testamentOrder: 13, bibleOrder: 13, newTestament: false, chapterCount: 29, name: "1 Chronicles", abbreviations: ["1 Chr", "1 Ch"] },
  { testamentOrder: 14, bibleOrder: 14, newTestament: false, chapterCount: 36, name: "2 Chronicles", abbreviations: ["2 Chr", "2 Ch", "2 Chron"] },
  { testamentOrder: 15, bibleOrder: 15, newTestament: false, chapterCount: 10, name: "Ezra", abbreviations: ["Ezra", "Ezr"] },
  { testamentOrder: 16, bibleOrder: 16, newTestament: false, chapterCount: 13, name: "Nehemiah", abbreviations: ["Neh", "Ne"] },
  { testamentOrder: 17, bibleOrder: 17, newTestament: false, chapterCount: 10, name: "Esther", abbreviations: ["Esth 1", "Est", "Es"] },
  { testamentOrder: 18, bibleOrder: 18, newTestament: false, chapterCount: 42, name: "Job", abbreviations: ["Job", "Jb"] },
  { testamentOrder: 19, bibleOrder: 19, newTestament: false, chapterCount: 150, name: "Psalms", abbreviations: ["Ps", "Psalm", "Pslm", "Psa", "Psm"] },
  { testamentOrder: 20, bibleOrder: 20, newTestament: false, chapterCount: 31, name: "Proverbs", abbreviations: ["Prov", "Pro", "Prv", "Pr"] },
  { testamentOrder: 21, bibleOrder: 21, newTestament: false, chapterCount: 12, name: "Ecclesiastes", abbreviations: ["Ecc1", "Eccles", "Eccle", "Ecc", "Ec"] },
  { testamentOrder: 22, bibleOrder: 22, newTestament: false, chapterCount: 8, name: "Song of Songs", abbreviations: ["Song", "Song of Solomon"] },
  { testamentOrder: 23, bibleOrder: 23, newTestament: false, chapterCount: 66, name: "Isaiah", abbreviations: ["Isa", "Is"] },
  { testamentOrder: 24, bibleOrder: 24, newTestament: false, chapterCount: 52, name: "Jeremiah", abbreviations: ["Jer", "Je", "Jr"] },
  { testamentOrder: 25, bibleOrder: 25, newTestament: false, chapterCount: 5, name: "Lamentations", abbreviations: ["Lam", "La"] },
  { testamentOrder: 26, bibleOrder: 26, newTestament: false, chapterCount: 48, name: "Ezekiel", abbreviations: ["Ezek", "Eze", "Ezk"] },
  { testamentOrder: 27, bibleOrder: 27, newTestament: false, chapterCount: 12, name: "Daniel", abbreviations: ["Dan", "Da", "Dn"] },
  { testamentOrder: 28, bibleOrder: 28, newTestament: false, chapterCount: 14, name: "Hosea", abbreviations: ["Hos", "Ho"] },
  { testamentOrder: 29, bibleOrder: 29, newTestament: false, chapterCount: 3, name: "Joel", abbreviations: ["Joel", "Jl"] },
  { testamentOrder: 30, bibleOrder: 30, newTestament: false, chapterCount: 9, name: "Amos", abbreviations: ["Am"] },
  { testamentOrder: 31, bibleOrder: 31, newTestament: false, chapterCount: 1, name: "Obadiah", abbreviations: ["Obad"] },
  { testamentOrder: 32, bibleOrder: 32, newTestament: false, chapterCount: 4, name: "Jonah", abbreviations: ["Jon", "Jnh"] },
  { testamentOrder: 33, bibleOrder: 33, newTestament: false, chapterCount: 7, name: "Micah", abbreviations: ["Mic", "Mc"] },
  { testamentOrder: 34, bibleOrder: 34, newTestament: false, chapterCount: 3, name: "Nahum", abbreviations: ["Nah", "Na"] },
  { testamentOrder: 35, bibleOrder: 35, newTestament: false, chapterCount: 3, name: "Habakkuk", abbreviations: ["Hab", "Hb"] },
  { testamentOrder: 36, bibleOrder: 36, newTestament: false, chapterCount: 3, name: "Zephaniah", abbreviations: ["Zeph", "Zep", "Zp"] },
  { testamentOrder: 37, bibleOrder: 37, newTestament: false, chapterCount: 2, name: "Haggai", abbreviations: ["Hag", "Hg"] },
  { testamentOrder: 38, bibleOrder: 38, newTestament: false, chapterCount: 14, name: "Zechariah", abbreviations: ["Zech", "Zec", "Zc"] },
  { testamentOrder: 39, bibleOrder: 39, newTestament: false, chapterCount: 4, name: "Malachi", abbreviations: ["Mal", "Ml"] },
  { testamentOrder: 1, bibleOrder: 40, newTestament: true, chapterCount: 28, name: "Matthew", abbreviations: ["Mt", "Matt"] },
  { testamentOrder: 2, bibleOrder: 41, newTestament: true, chapterCount: 16, name: "Mark", abbreviations: ["Mk", "Mrk"] },
  { testamentOrder: 3, bibleOrder: 42, newTestament: true, chapterCount: 24, name: "Luke", abbreviations: ["Lk", "Luk"] },
  { testamentOrder: 4, bibleOrder: 43, newTestament: true, chapterCount: 21, name: "John", abbreviations: ["Jn", "Jhn"] },
  { testamentOrder: 5, bibleOrder: 44, newTestament: true, chapterCount: 28, name: "Acts", abbreviations: [] },
  { testamentOrder: 6, bibleOrder: 45, newTestament: true, chapterCount: 16, name: "Romans", abbreviations: ["Rom", "Ro", "Rm"] },
  { testamentOrder: 7, bibleOrder: 46, newTestament: true, chapterCount: 16, name: "1 Corinthians", abbreviations: ["1 Cor", "1 Co"] },
  { testamentOrder: 8, bibleOrder: 47, newTestament: true, chapterCount: 13, name: "2 Corinthians", abbreviations: ["2 Cor", "2 Co"] },
  { testamentOrder: 9, bibleOrder: 48, newTestament: true, chapterCount: 6, name: "Galatians", abbreviations: ["Gal", "Ga"] },
  { testamentOrder: 10, bibleOrder: 49, newTestament: true, chapterCount: 6, name: "Ephesians", abbreviations: ["Eph", "Ephes"] },
  { testamentOrder: 11, bibleOrder: 50, newTestament: true, chapterCount: 4, name: "Philippians", abbreviations: ["Phil", "Php", "Pp"] },
  { testamentOrder: 12, bibleOrder: 51, newTestament: true, chapterCount: 4, name: "Colossians", abbreviations: ["Col"] },
  { testamentOrder: 13, bibleOrder: 52, newTestament: true, chapterCount: 5, name: "1 Thessalonians", abbreviations: ["1 Thess", "1 Thes", "1 Th"] },
  { testamentOrder: 14, bibleOrder: 53, newTestament: true, chapterCount: 3, name: "2 Thessalonians", abbreviations: ["2 Thess", "2 Thes", "2 Th"] },
  { testamentOrder: 15, bibleOrder: 54, newTestament: true, chapterCount: 6, name: "1 Timothy", abbreviations: ["1 Tim", "1 Ti"] },
  { testamentOrder: 16, bibleOrder: 55, newTestament: true, chapterCount: 4, name: "2 Timothy", abbreviations: ["2 Tim", "2 Ti"] },
  { testamentOrder: 17, bibleOrder: 56, newTestament: true, chapterCount: 3, name: "Titus", abbreviations: ["Tit", "Ti"] },
  { testamentOrder: 18, bibleOrder: 57, newTestament: true, chapterCount: 1, name: "Philemon", abbreviations: ["Philem", "Phlm", "Phm", "Pm"] },
  { testamentOrder: 19, bibleOrder: 58, newTestament: true, chapterCount: 13, name: "Hebrews", abbreviations: ["Heb"] },
  { testamentOrder: 20, bibleOrder: 59, newTestament: true, chapterCount: 5, name: "James", abbreviations: ["Jas", "Jm"] },
  { testamentOrder: 21, bibleOrder: 60, newTestament: true, chapterCount: 5, name: "1 Peter", abbreviations: ["1 Pet", "1 Pe", "1 Pt", "1 P"] },
  { testamentOrder: 22, bibleOrder: 61, newTestament: true, chapterCount: 3, name: "2 Peter", abbreviations: ["2 Pet", "2 Pe", "2 Pt", "2 P"] },
  { testamentOrder: 23, bibleOrder: 62, newTestament: true, chapterCount: 5, name: "1 John", abbreviations: ["1 Jn", "1 Jhn", "1 J"] },
  { testamentOrder: 24, bibleOrder: 63, newTestament: true, chapterCount: 1, name: "2 John", abbreviations: ["2 Jn", "2 Jhn", "2 J"] },
  { testamentOrder: 25, bibleOrder: 64, newTestament: true, chapterCount: 1, name: "3 John", abbreviations: ["3 Jn", "3 Jhn", "3 J"] },
  { testamentOrder: 26, bibleOrder: 65, newTestament: true, chapterCount: 1, name: "Jude", abbreviations: ["Jude", "Jud", "Jd"] },
  { testamentOrder: 27, bibleOrder: 66, newTestament: true, chapterCount: 22, name: "Revelation", abbreviations: ["Rev"] },
];

export default bibleBooks;
